/**
 * Ordinary People — Seed Data Script
 * 20 Italian consumer personas + 6 macroeconomic regimes
 * All psychographics grounded in ISTAT 2024 + 25-book bibliography
 */
import { drizzle } from "drizzle-orm/mysql2";
import { personas, regimes } from "./drizzle/schema.ts";

const db = drizzle(process.env.DATABASE_URL);

// ─── 20 PERSONAS ─────────────────────────────────────────────────────
const personaData = [
  {
    archetypeId: "studente_urbano",
    label: "Studente Urbano",
    ageMin: 19, ageMax: 25, incomeBand: "very_low", geo: "urban", education: "degree", householdType: "shared",
    noveltySeeking: 0.85, statusOrientation: 0.35, priceSensitivity: 0.90, riskAversion: 0.30,
    emotionalSusceptibility: 0.75, identityDefensiveness: 0.25,
    conformismIndex: 0.30, authorityTrust: 0.25, delayedGratification: 0.35, culturalCapital: 0.65, locusOfControl: 0.60,
    populationShare: 0.06, marketSpendShare: 0.02,
    topicAffinities: { sustainability: 0.8, tech: 0.7, fashion: 0.6, food: 0.5, luxury: 0.1 },
    formatAffinities: { short_video: 0.9, story: 0.8, carousel: 0.6, image: 0.5, long_article: 0.3 },
    channelUsage: { tiktok: 0.9, instagram: 0.85, youtube: 0.7, twitter: 0.4, facebook: 0.1, linkedin: 0.1 },
    comfortablePriceMid: 25, comfortablePriceRange: 20,
    identityProfile: { progressive: 0.8, cosmopolitan: 0.7, eco_conscious: 0.7, traditional: 0.1 },
    mediaDiet: { social: 0.9, streaming: 0.8, podcasts: 0.5, tv: 0.1, newspapers: 0.05 },
    referenceGroup: "creativo_freelance", rejectionGroup: "pensionata_tv",
    generationalCohort: "gen_z",
    bibliographyNotes: "Bauman: identità liquida, consumo come costruzione del sé. Giddens: reflexive project, lifestyle choices come identità. Kahneman: Sistema 1 domina, decisioni impulsive. Piketty: bottom quintile, alta price_sensitivity strutturale. ISTAT 2024: reddito medio studenti fuori sede ~600€/mese."
  },
  {
    archetypeId: "giovane_precario",
    label: "Giovane Precario Digitale",
    ageMin: 25, ageMax: 34, incomeBand: "low", geo: "urban", education: "degree", householdType: "single",
    noveltySeeking: 0.80, statusOrientation: 0.45, priceSensitivity: 0.85, riskAversion: 0.40,
    emotionalSusceptibility: 0.80, identityDefensiveness: 0.35,
    conformismIndex: 0.25, authorityTrust: 0.20, delayedGratification: 0.30, culturalCapital: 0.60, locusOfControl: 0.35,
    populationShare: 0.08, marketSpendShare: 0.04,
    topicAffinities: { tech: 0.8, entertainment: 0.7, food: 0.6, fashion: 0.5, wellness: 0.4 },
    formatAffinities: { short_video: 0.9, story: 0.8, image: 0.6, carousel: 0.5, long_article: 0.2 },
    channelUsage: { instagram: 0.9, tiktok: 0.85, youtube: 0.7, twitter: 0.5, facebook: 0.3, linkedin: 0.4 },
    comfortablePriceMid: 40, comfortablePriceRange: 30,
    identityProfile: { progressive: 0.7, digital_native: 0.9, frustrated: 0.6, traditional: 0.1 },
    mediaDiet: { social: 0.9, streaming: 0.85, podcasts: 0.6, tv: 0.15, newspapers: 0.05 },
    referenceGroup: "influencer_creator", rejectionGroup: "manager_corporate",
    generationalCohort: "millennial",
    bibliographyNotes: "Fromm: libertà senza sicurezza genera ansia. Hoffer: frustrazione come motore di adesione a movimenti. Bauman: precarietà esistenziale, relazioni liquide. Polanyi: commodification del lavoro → insicurezza. ISTAT 2024: tasso disoccupazione giovanile 22.3%, contratti precari 40%+."
  },
  {
    archetypeId: "impiegato_famiglia",
    label: "Impiegato Medio con Famiglia",
    ageMin: 35, ageMax: 50, incomeBand: "medium", geo: "suburban", education: "degree", householdType: "family",
    noveltySeeking: 0.30, statusOrientation: 0.40, priceSensitivity: 0.70, riskAversion: 0.75,
    emotionalSusceptibility: 0.55, identityDefensiveness: 0.50,
    conformismIndex: 0.70, authorityTrust: 0.60, delayedGratification: 0.65, culturalCapital: 0.45, locusOfControl: 0.50,
    populationShare: 0.12, marketSpendShare: 0.14,
    topicAffinities: { family: 0.9, home: 0.8, food: 0.7, automotive: 0.6, tech: 0.4, fashion: 0.3 },
    formatAffinities: { image: 0.7, carousel: 0.6, long_article: 0.5, short_video: 0.4, story: 0.3 },
    channelUsage: { facebook: 0.8, instagram: 0.5, youtube: 0.6, whatsapp: 0.9, tiktok: 0.1, linkedin: 0.3 },
    comfortablePriceMid: 80, comfortablePriceRange: 50,
    identityProfile: { family_oriented: 0.9, practical: 0.8, traditional: 0.5, progressive: 0.3 },
    mediaDiet: { tv: 0.7, social: 0.5, newspapers: 0.3, streaming: 0.4, radio: 0.4 },
    referenceGroup: "libero_professionista", rejectionGroup: "studente_urbano",
    generationalCohort: "gen_x",
    bibliographyNotes: "Thaler: mental accounting rigido, budget per categorie. Kahneman: loss aversion alta per patrimonio familiare. Galbraith: conventional wisdom, resistenza al cambiamento. Bourdieu: petit-bourgeois habitus, aspirazione controllata. ISTAT 2024: spesa media famiglie 2.755€/mese."
  },
  {
    archetypeId: "libero_professionista",
    label: "Libero Professionista Urbano",
    ageMin: 30, ageMax: 50, incomeBand: "high", geo: "urban", education: "postgrad", householdType: "couple",
    noveltySeeking: 0.65, statusOrientation: 0.75, priceSensitivity: 0.35, riskAversion: 0.45,
    emotionalSusceptibility: 0.50, identityDefensiveness: 0.40,
    conformismIndex: 0.35, authorityTrust: 0.40, delayedGratification: 0.70, culturalCapital: 0.80, locusOfControl: 0.75,
    populationShare: 0.07, marketSpendShare: 0.12,
    topicAffinities: { design: 0.8, travel: 0.8, food: 0.7, tech: 0.7, luxury: 0.6, wellness: 0.6 },
    formatAffinities: { long_article: 0.7, carousel: 0.7, image: 0.6, short_video: 0.5, story: 0.4 },
    channelUsage: { instagram: 0.8, linkedin: 0.7, youtube: 0.6, twitter: 0.5, facebook: 0.3, tiktok: 0.2 },
    comfortablePriceMid: 200, comfortablePriceRange: 150,
    identityProfile: { cosmopolitan: 0.8, cultured: 0.8, progressive: 0.6, eco_conscious: 0.5 },
    mediaDiet: { social: 0.7, podcasts: 0.7, newspapers: 0.5, streaming: 0.5, tv: 0.2 },
    referenceGroup: "imprenditore_alto", rejectionGroup: "pensionata_tv",
    generationalCohort: "millennial",
    bibliographyNotes: "Bourdieu: capitale culturale + economico, gusto legittimo. Piketty: supermanager class, consumo ibrido. Giddens: reflexive modernity, scelte consapevoli. Veblen (via Douglas): conspicuous consumption selettiva."
  },
  {
    archetypeId: "imprenditore_alto",
    label: "Imprenditore Alto Reddito",
    ageMin: 40, ageMax: 65, incomeBand: "very_high", geo: "urban", education: "postgrad", householdType: "family",
    noveltySeeking: 0.50, statusOrientation: 0.90, priceSensitivity: 0.10, riskAversion: 0.30,
    emotionalSusceptibility: 0.35, identityDefensiveness: 0.55,
    conformismIndex: 0.40, authorityTrust: 0.50, delayedGratification: 0.85, culturalCapital: 0.70, locusOfControl: 0.90,
    populationShare: 0.03, marketSpendShare: 0.15,
    topicAffinities: { luxury: 0.9, travel: 0.8, automotive: 0.8, real_estate: 0.7, finance: 0.7, design: 0.6 },
    formatAffinities: { long_article: 0.7, image: 0.7, carousel: 0.5, short_video: 0.3, story: 0.2 },
    channelUsage: { linkedin: 0.8, instagram: 0.6, youtube: 0.5, facebook: 0.4, twitter: 0.3, tiktok: 0.05 },
    comfortablePriceMid: 1000, comfortablePriceRange: 800,
    identityProfile: { elite: 0.9, traditional: 0.5, cosmopolitan: 0.7, patriotic: 0.4 },
    mediaDiet: { newspapers: 0.7, social: 0.5, tv: 0.4, podcasts: 0.4, streaming: 0.3 },
    referenceGroup: "manager_corporate", rejectionGroup: "giovane_precario",
    generationalCohort: "boomer",
    bibliographyNotes: "Piketty: top 1%, r > g beneficiario diretto. Bourdieu: classe dominante, gusto come potere. Veblen: conspicuous consumption come dovere sociale. Thaler: endowment effect forte su patrimonio. ISTAT: top decile detiene 50%+ ricchezza netta."
  },
  {
    archetypeId: "casalinga_provincia",
    label: "Casalinga Provincia 45-60",
    ageMin: 45, ageMax: 60, incomeBand: "medium", geo: "suburban", education: "secondary", householdType: "family",
    noveltySeeking: 0.20, statusOrientation: 0.35, priceSensitivity: 0.75, riskAversion: 0.80,
    emotionalSusceptibility: 0.70, identityDefensiveness: 0.70,
    conformismIndex: 0.80, authorityTrust: 0.75, delayedGratification: 0.60, culturalCapital: 0.25, locusOfControl: 0.30,
    populationShare: 0.08, marketSpendShare: 0.07,
    topicAffinities: { family: 0.9, food: 0.9, home: 0.8, health: 0.7, fashion: 0.4, wellness: 0.3 },
    formatAffinities: { image: 0.7, carousel: 0.6, story: 0.4, long_article: 0.3, short_video: 0.3 },
    channelUsage: { facebook: 0.9, whatsapp: 0.9, instagram: 0.4, youtube: 0.3, tiktok: 0.05, linkedin: 0.0 },
    comfortablePriceMid: 50, comfortablePriceRange: 35,
    identityProfile: { traditional: 0.9, family_oriented: 0.9, patriotic: 0.7, religious: 0.5 },
    mediaDiet: { tv: 0.9, social: 0.5, radio: 0.4, newspapers: 0.2, streaming: 0.1 },
    referenceGroup: "impiegato_famiglia", rejectionGroup: "influencer_creator",
    generationalCohort: "gen_x",
    bibliographyNotes: "Fromm: conformismo automaton, sicurezza nella tradizione. Haidt: moral foundations tradizionali (loyalty, authority, sanctity). Anderson: identità nazionale forte, 'Made in Italy'. Adorno: cultura industriale come comfort zone. ISTAT: 31.1% famiglie limita spesa alimentare."
  },
  {
    archetypeId: "pensionata_tv",
    label: "Pensionata TV/Facebook",
    ageMin: 65, ageMax: 80, incomeBand: "low_medium", geo: "suburban", education: "secondary", householdType: "couple",
    noveltySeeking: 0.10, statusOrientation: 0.25, priceSensitivity: 0.80, riskAversion: 0.90,
    emotionalSusceptibility: 0.75, identityDefensiveness: 0.65,
    conformismIndex: 0.85, authorityTrust: 0.80, delayedGratification: 0.70, culturalCapital: 0.20, locusOfControl: 0.20,
    populationShare: 0.10, marketSpendShare: 0.06,
    topicAffinities: { health: 0.9, food: 0.8, family: 0.8, home: 0.6, news: 0.7, religion: 0.4 },
    formatAffinities: { image: 0.6, long_article: 0.5, carousel: 0.3, short_video: 0.2, story: 0.1 },
    channelUsage: { facebook: 0.8, whatsapp: 0.9, youtube: 0.3, instagram: 0.1, tiktok: 0.0, linkedin: 0.0 },
    comfortablePriceMid: 30, comfortablePriceRange: 20,
    identityProfile: { traditional: 0.9, patriotic: 0.8, religious: 0.6, family_oriented: 0.8 },
    mediaDiet: { tv: 0.95, radio: 0.5, newspapers: 0.4, social: 0.3, streaming: 0.05 },
    referenceGroup: "casalinga_provincia", rejectionGroup: "studente_urbano",
    generationalCohort: "silent",
    bibliographyNotes: "Le Bon: suggestibilità mediatica alta. Chomsky: manufacturing consent via TV. Thaler: status quo bias massimo. Kahneman: availability heuristic dominante. ISTAT: pensione media 1.153€/mese, 23.5% popolazione over 65."
  },
  {
    archetypeId: "operaio_industriale",
    label: "Operaio Industriale",
    ageMin: 30, ageMax: 55, incomeBand: "medium", geo: "suburban", education: "secondary", householdType: "family",
    noveltySeeking: 0.25, statusOrientation: 0.30, priceSensitivity: 0.80, riskAversion: 0.70,
    emotionalSusceptibility: 0.55, identityDefensiveness: 0.60,
    conformismIndex: 0.70, authorityTrust: 0.55, delayedGratification: 0.55, culturalCapital: 0.25, locusOfControl: 0.35,
    populationShare: 0.09, marketSpendShare: 0.08,
    topicAffinities: { automotive: 0.8, sport: 0.8, food: 0.7, tech: 0.4, home: 0.6, family: 0.6 },
    formatAffinities: { short_video: 0.6, image: 0.6, carousel: 0.4, story: 0.3, long_article: 0.2 },
    channelUsage: { facebook: 0.7, whatsapp: 0.9, youtube: 0.7, instagram: 0.4, tiktok: 0.2, linkedin: 0.05 },
    comfortablePriceMid: 60, comfortablePriceRange: 40,
    identityProfile: { working_class: 0.8, patriotic: 0.6, traditional: 0.6, practical: 0.8 },
    mediaDiet: { tv: 0.7, social: 0.5, radio: 0.5, streaming: 0.3, newspapers: 0.2 },
    referenceGroup: "artigiano_commerciante", rejectionGroup: "imprenditore_alto",
    generationalCohort: "gen_x",
    bibliographyNotes: "Polanyi: classe lavoratrice, double movement protettivo. Hobsbawm: identità di classe in declino. Fromm: alienazione dal lavoro. Piketty: classe media compressa. ISTAT: reddito medio operaio ~1.400€/mese netto."
  },
  {
    archetypeId: "insegnante_pubblico",
    label: "Insegnante / Impiegato Pubblico",
    ageMin: 30, ageMax: 60, incomeBand: "medium", geo: "urban", education: "degree", householdType: "family",
    noveltySeeking: 0.40, statusOrientation: 0.35, priceSensitivity: 0.65, riskAversion: 0.65,
    emotionalSusceptibility: 0.60, identityDefensiveness: 0.45,
    conformismIndex: 0.60, authorityTrust: 0.65, delayedGratification: 0.70, culturalCapital: 0.65, locusOfControl: 0.45,
    populationShare: 0.08, marketSpendShare: 0.07,
    topicAffinities: { culture: 0.8, education: 0.8, travel: 0.6, food: 0.6, books: 0.7, wellness: 0.5 },
    formatAffinities: { long_article: 0.7, carousel: 0.6, image: 0.5, short_video: 0.4, story: 0.3 },
    channelUsage: { facebook: 0.7, instagram: 0.5, youtube: 0.5, whatsapp: 0.8, linkedin: 0.3, tiktok: 0.1 },
    comfortablePriceMid: 70, comfortablePriceRange: 45,
    identityProfile: { cultured: 0.7, progressive: 0.5, traditional: 0.4, eco_conscious: 0.5 },
    mediaDiet: { newspapers: 0.6, tv: 0.5, social: 0.5, podcasts: 0.4, streaming: 0.4 },
    referenceGroup: "libero_professionista", rejectionGroup: "influencer_creator",
    generationalCohort: "gen_x",
    bibliographyNotes: "Bourdieu: capitale culturale alto, economico medio. Galbraith: conventional wisdom, stabilità come valore. Giddens: reflexive ma conservatore. Thaler: mental accounting pubblico/privato. ISTAT: stipendio medio insegnanti ~1.500€/mese."
  },
  {
    archetypeId: "creativo_freelance",
    label: "Creativo Freelance Urbano",
    ageMin: 25, ageMax: 40, incomeBand: "low_medium", geo: "urban", education: "degree", householdType: "single",
    noveltySeeking: 0.90, statusOrientation: 0.55, priceSensitivity: 0.65, riskAversion: 0.25,
    emotionalSusceptibility: 0.70, identityDefensiveness: 0.30,
    conformismIndex: 0.15, authorityTrust: 0.20, delayedGratification: 0.25, culturalCapital: 0.85, locusOfControl: 0.65,
    populationShare: 0.04, marketSpendShare: 0.03,
    topicAffinities: { design: 0.9, art: 0.9, tech: 0.7, sustainability: 0.7, fashion: 0.7, food: 0.6 },
    formatAffinities: { short_video: 0.8, image: 0.8, story: 0.7, carousel: 0.6, long_article: 0.5 },
    channelUsage: { instagram: 0.9, tiktok: 0.7, youtube: 0.7, twitter: 0.6, linkedin: 0.4, facebook: 0.2 },
    comfortablePriceMid: 50, comfortablePriceRange: 40,
    identityProfile: { creative: 0.9, cosmopolitan: 0.8, progressive: 0.8, eco_conscious: 0.6 },
    mediaDiet: { social: 0.9, podcasts: 0.7, streaming: 0.6, newspapers: 0.3, tv: 0.1 },
    referenceGroup: "libero_professionista", rejectionGroup: "operaio_industriale",
    generationalCohort: "millennial",
    bibliographyNotes: "Bourdieu: capitale culturale alto, economico basso → tensione. Bauman: liquidità come stile di vita. Giddens: reflexive project massimo. Florida (via Bauman): creative class precaria. ISTAT: reddito medio freelance ~1.100€/mese."
  },
  {
    archetypeId: "manager_corporate",
    label: "Manager Corporate",
    ageMin: 35, ageMax: 55, incomeBand: "high", geo: "urban", education: "postgrad", householdType: "family",
    noveltySeeking: 0.50, statusOrientation: 0.80, priceSensitivity: 0.25, riskAversion: 0.40,
    emotionalSusceptibility: 0.40, identityDefensiveness: 0.50,
    conformismIndex: 0.55, authorityTrust: 0.55, delayedGratification: 0.80, culturalCapital: 0.65, locusOfControl: 0.80,
    populationShare: 0.05, marketSpendShare: 0.11,
    topicAffinities: { finance: 0.8, tech: 0.7, luxury: 0.7, travel: 0.7, automotive: 0.6, wellness: 0.5 },
    formatAffinities: { long_article: 0.7, carousel: 0.6, image: 0.5, short_video: 0.4, story: 0.3 },
    channelUsage: { linkedin: 0.9, instagram: 0.6, youtube: 0.5, twitter: 0.5, facebook: 0.3, tiktok: 0.1 },
    comfortablePriceMid: 300, comfortablePriceRange: 250,
    identityProfile: { professional: 0.9, cosmopolitan: 0.7, elite: 0.6, progressive: 0.4 },
    mediaDiet: { newspapers: 0.7, social: 0.6, podcasts: 0.6, tv: 0.3, streaming: 0.4 },
    referenceGroup: "imprenditore_alto", rejectionGroup: "giovane_precario",
    generationalCohort: "gen_x",
    bibliographyNotes: "Piketty: supermanager, compensi 50-100x mediano. Bourdieu: campo del potere economico. Thaler: overconfidence bias. Duke: probabilistic thinking professionale."
  },
  {
    archetypeId: "disoccupato_marginale",
    label: "Disoccupato / Marginale",
    ageMin: 25, ageMax: 55, incomeBand: "very_low", geo: "suburban", education: "secondary", householdType: "single",
    noveltySeeking: 0.20, statusOrientation: 0.15, priceSensitivity: 0.95, riskAversion: 0.80,
    emotionalSusceptibility: 0.85, identityDefensiveness: 0.50,
    conformismIndex: 0.55, authorityTrust: 0.30, delayedGratification: 0.15, culturalCapital: 0.15, locusOfControl: 0.15,
    populationShare: 0.06, marketSpendShare: 0.01,
    topicAffinities: { food: 0.8, entertainment: 0.6, sport: 0.5, news: 0.5, health: 0.4 },
    formatAffinities: { short_video: 0.7, image: 0.5, story: 0.4, carousel: 0.3, long_article: 0.1 },
    channelUsage: { facebook: 0.7, whatsapp: 0.8, youtube: 0.6, tiktok: 0.4, instagram: 0.3, linkedin: 0.0 },
    comfortablePriceMid: 15, comfortablePriceRange: 10,
    identityProfile: { frustrated: 0.8, working_class: 0.5, traditional: 0.4, patriotic: 0.3 },
    mediaDiet: { tv: 0.8, social: 0.6, radio: 0.3, streaming: 0.2, newspapers: 0.1 },
    referenceGroup: "operaio_industriale", rejectionGroup: "imprenditore_alto",
    generationalCohort: "millennial",
    bibliographyNotes: "Piketty: bottom quintile, escluso da r > g. Arendt: atomizzazione sociale, vulnerabilità. Hoffer: frustrazione massima, potenziale true believer. Polanyi: vittima della commodification. ISTAT: 9.8% povertà assoluta."
  },
  {
    archetypeId: "neolaureata_ambiziosa",
    label: "Neolaureata Ambiziosa",
    ageMin: 23, ageMax: 30, incomeBand: "low", geo: "urban", education: "postgrad", householdType: "shared",
    noveltySeeking: 0.75, statusOrientation: 0.65, priceSensitivity: 0.70, riskAversion: 0.35,
    emotionalSusceptibility: 0.65, identityDefensiveness: 0.30,
    conformismIndex: 0.35, authorityTrust: 0.40, delayedGratification: 0.60, culturalCapital: 0.75, locusOfControl: 0.70,
    populationShare: 0.05, marketSpendShare: 0.03,
    topicAffinities: { career: 0.9, fashion: 0.7, travel: 0.7, wellness: 0.6, luxury: 0.5, tech: 0.6 },
    formatAffinities: { short_video: 0.8, carousel: 0.7, image: 0.7, story: 0.6, long_article: 0.5 },
    channelUsage: { instagram: 0.9, linkedin: 0.8, tiktok: 0.6, youtube: 0.5, twitter: 0.4, facebook: 0.2 },
    comfortablePriceMid: 60, comfortablePriceRange: 45,
    identityProfile: { ambitious: 0.9, cosmopolitan: 0.7, progressive: 0.6, cultured: 0.6 },
    mediaDiet: { social: 0.8, podcasts: 0.7, streaming: 0.5, newspapers: 0.3, tv: 0.15 },
    referenceGroup: "libero_professionista", rejectionGroup: "casalinga_provincia",
    generationalCohort: "gen_z",
    bibliographyNotes: "Bourdieu: capitale culturale in conversione. Bauman: identità in costruzione. Giddens: reflexive project intenso. Piketty: mobilità sociale come promessa. ISTAT: tasso occupazione laureati 75%, ma 30% sottoinquadrati."
  },
  {
    archetypeId: "artigiano_commerciante",
    label: "Artigiano / Commerciante",
    ageMin: 35, ageMax: 60, incomeBand: "medium", geo: "rural", education: "secondary", householdType: "family",
    noveltySeeking: 0.30, statusOrientation: 0.40, priceSensitivity: 0.60, riskAversion: 0.60,
    emotionalSusceptibility: 0.50, identityDefensiveness: 0.65,
    conformismIndex: 0.60, authorityTrust: 0.50, delayedGratification: 0.65, culturalCapital: 0.35, locusOfControl: 0.60,
    populationShare: 0.06, marketSpendShare: 0.06,
    topicAffinities: { food: 0.8, home: 0.7, automotive: 0.7, sport: 0.6, local: 0.8, family: 0.6 },
    formatAffinities: { image: 0.7, carousel: 0.5, short_video: 0.5, long_article: 0.4, story: 0.3 },
    channelUsage: { facebook: 0.8, whatsapp: 0.9, instagram: 0.5, youtube: 0.5, tiktok: 0.1, linkedin: 0.1 },
    comfortablePriceMid: 80, comfortablePriceRange: 55,
    identityProfile: { traditional: 0.7, patriotic: 0.7, practical: 0.8, local: 0.8 },
    mediaDiet: { tv: 0.6, radio: 0.5, social: 0.5, newspapers: 0.4, streaming: 0.2 },
    referenceGroup: "impiegato_famiglia", rejectionGroup: "creativo_freelance",
    generationalCohort: "gen_x",
    bibliographyNotes: "Polanyi: economia embedded, relazioni sociali. Anderson: identità locale forte. Thaler: mental accounting del piccolo imprenditore. Hobsbawm: classe in trasformazione."
  },
  {
    archetypeId: "early_adopter",
    label: "Early Adopter Tech/Fashion",
    ageMin: 22, ageMax: 38, incomeBand: "medium_high", geo: "urban", education: "degree", householdType: "single",
    noveltySeeking: 0.95, statusOrientation: 0.70, priceSensitivity: 0.40, riskAversion: 0.15,
    emotionalSusceptibility: 0.60, identityDefensiveness: 0.25,
    conformismIndex: 0.10, authorityTrust: 0.25, delayedGratification: 0.30, culturalCapital: 0.70, locusOfControl: 0.80,
    populationShare: 0.03, marketSpendShare: 0.05,
    topicAffinities: { tech: 0.95, fashion: 0.8, design: 0.8, gadgets: 0.9, sustainability: 0.5, luxury: 0.6 },
    formatAffinities: { short_video: 0.9, story: 0.8, carousel: 0.7, image: 0.6, long_article: 0.5 },
    channelUsage: { tiktok: 0.9, instagram: 0.9, youtube: 0.8, twitter: 0.7, linkedin: 0.4, facebook: 0.1 },
    comfortablePriceMid: 150, comfortablePriceRange: 120,
    identityProfile: { innovative: 0.9, cosmopolitan: 0.8, digital_native: 0.9, progressive: 0.6 },
    mediaDiet: { social: 0.95, podcasts: 0.7, streaming: 0.6, newsletters: 0.5, tv: 0.05 },
    referenceGroup: "influencer_creator", rejectionGroup: "pensionata_tv",
    generationalCohort: "gen_z",
    bibliographyNotes: "Schelling: innovatori nella curva di adozione (2.5%). Bauman: liquidità come valore. Giddens: lifestyle politics. Bourdieu: nuovo capitale culturale digitale."
  },
  // ─── 5 NUOVE PERSONAS (v0.1 — Gap Analysis) ─────────────────────
  {
    archetypeId: "immigrato_prima_gen",
    label: "Immigrato Prima Generazione",
    ageMin: 25, ageMax: 50, incomeBand: "low", geo: "urban", education: "secondary", householdType: "family",
    noveltySeeking: 0.35, statusOrientation: 0.30, priceSensitivity: 0.90, riskAversion: 0.65,
    emotionalSusceptibility: 0.65, identityDefensiveness: 0.75,
    conformismIndex: 0.65, authorityTrust: 0.45, delayedGratification: 0.70, culturalCapital: 0.30, locusOfControl: 0.40,
    populationShare: 0.08, marketSpendShare: 0.04,
    topicAffinities: { food: 0.8, family: 0.9, home: 0.7, remittances: 0.6, religion: 0.5, education: 0.6 },
    formatAffinities: { short_video: 0.7, image: 0.6, story: 0.5, carousel: 0.4, long_article: 0.2 },
    channelUsage: { whatsapp: 0.95, facebook: 0.7, youtube: 0.6, tiktok: 0.4, instagram: 0.4, linkedin: 0.05 },
    comfortablePriceMid: 30, comfortablePriceRange: 20,
    identityProfile: { diaspora: 0.8, traditional: 0.7, family_oriented: 0.9, religious: 0.6 },
    mediaDiet: { social: 0.6, tv: 0.5, radio: 0.4, streaming: 0.3, newspapers: 0.1 },
    referenceGroup: "operaio_industriale", rejectionGroup: null,
    generationalCohort: "millennial",
    bibliographyNotes: "Anderson: comunità immaginate transnazionali. Polanyi: doppia commodification (lavoro + cultura). Fromm: libertà come sradicamento. Haidt: moral foundations tradizionali forti. ISTAT: 5.2M residenti stranieri, reddito medio 30% inferiore."
  },
  {
    archetypeId: "influencer_creator",
    label: "Influencer / Content Creator",
    ageMin: 20, ageMax: 35, incomeBand: "medium_high", geo: "urban", education: "degree", householdType: "single",
    noveltySeeking: 0.90, statusOrientation: 0.85, priceSensitivity: 0.30, riskAversion: 0.20,
    emotionalSusceptibility: 0.65, identityDefensiveness: 0.20,
    conformismIndex: 0.20, authorityTrust: 0.15, delayedGratification: 0.20, culturalCapital: 0.60, locusOfControl: 0.75,
    populationShare: 0.02, marketSpendShare: 0.04,
    topicAffinities: { fashion: 0.9, beauty: 0.8, travel: 0.8, food: 0.7, tech: 0.7, luxury: 0.7 },
    formatAffinities: { short_video: 0.95, story: 0.9, image: 0.8, carousel: 0.7, long_article: 0.2 },
    channelUsage: { instagram: 0.95, tiktok: 0.95, youtube: 0.8, twitter: 0.5, linkedin: 0.3, facebook: 0.2 },
    comfortablePriceMid: 120, comfortablePriceRange: 100,
    identityProfile: { digital_native: 0.95, creative: 0.8, cosmopolitan: 0.8, innovative: 0.7 },
    mediaDiet: { social: 0.98, streaming: 0.6, podcasts: 0.5, tv: 0.05, newspapers: 0.02 },
    referenceGroup: "early_adopter", rejectionGroup: "pensionata_tv",
    generationalCohort: "gen_z",
    bibliographyNotes: "Bernays: engineering of consent 2.0, influencer come propagandista moderno. Adorno: pseudo-individualità digitale. Bourdieu: nuovo capitale culturale = follower count. Cialdini: social proof incarnato. Le Bon: leader d'opinione nelle masse digitali."
  },
  {
    archetypeId: "boomer_benestante",
    label: "Boomer Benestante",
    ageMin: 58, ageMax: 75, incomeBand: "high", geo: "suburban", education: "degree", householdType: "couple",
    noveltySeeking: 0.25, statusOrientation: 0.65, priceSensitivity: 0.30, riskAversion: 0.60,
    emotionalSusceptibility: 0.45, identityDefensiveness: 0.60,
    conformismIndex: 0.65, authorityTrust: 0.70, delayedGratification: 0.80, culturalCapital: 0.55, locusOfControl: 0.65,
    populationShare: 0.06, marketSpendShare: 0.10,
    topicAffinities: { travel: 0.8, health: 0.8, food: 0.7, real_estate: 0.7, culture: 0.6, luxury: 0.6 },
    formatAffinities: { long_article: 0.7, image: 0.6, carousel: 0.5, short_video: 0.3, story: 0.2 },
    channelUsage: { facebook: 0.7, whatsapp: 0.8, youtube: 0.5, instagram: 0.3, linkedin: 0.3, tiktok: 0.02 },
    comfortablePriceMid: 250, comfortablePriceRange: 200,
    identityProfile: { traditional: 0.7, patriotic: 0.6, elite: 0.5, cultured: 0.5 },
    mediaDiet: { tv: 0.7, newspapers: 0.7, social: 0.4, radio: 0.4, streaming: 0.2 },
    referenceGroup: "imprenditore_alto", rejectionGroup: "giovane_precario",
    generationalCohort: "boomer",
    bibliographyNotes: "Hobsbawm: generazione dell'Età dell'Oro, aspettative di crescita permanente. Galbraith: affluent society come normalità. Thaler: endowment effect massimo su patrimonio accumulato. Piketty: generazione che ha beneficiato di r > g. ISTAT: patrimonio medio over-60 3x rispetto a under-35."
  },
  {
    archetypeId: "neet",
    label: "NEET (Not in Education, Employment, or Training)",
    ageMin: 18, ageMax: 30, incomeBand: "very_low", geo: "suburban", education: "secondary", householdType: "family",
    noveltySeeking: 0.40, statusOrientation: 0.20, priceSensitivity: 0.95, riskAversion: 0.70,
    emotionalSusceptibility: 0.85, identityDefensiveness: 0.45,
    conformismIndex: 0.50, authorityTrust: 0.15, delayedGratification: 0.10, culturalCapital: 0.20, locusOfControl: 0.15,
    populationShare: 0.05, marketSpendShare: 0.01,
    topicAffinities: { gaming: 0.9, entertainment: 0.8, sport: 0.6, food: 0.5, tech: 0.5 },
    formatAffinities: { short_video: 0.9, story: 0.7, image: 0.5, carousel: 0.3, long_article: 0.1 },
    channelUsage: { tiktok: 0.8, youtube: 0.9, instagram: 0.6, twitch: 0.5, facebook: 0.3, linkedin: 0.0 },
    comfortablePriceMid: 15, comfortablePriceRange: 10,
    identityProfile: { frustrated: 0.7, digital_native: 0.7, isolated: 0.6, traditional: 0.2 },
    mediaDiet: { streaming: 0.9, social: 0.8, gaming: 0.8, tv: 0.3, newspapers: 0.02 },
    referenceGroup: "studente_urbano", rejectionGroup: "manager_corporate",
    generationalCohort: "gen_z",
    bibliographyNotes: "Hoffer: frustrazione senza canale → apatia o radicalizzazione. Fromm: escape from freedom via intrattenimento passivo. Arendt: atomizzazione sociale, vulnerabilità a propaganda. Bauman: wasted lives, scarti della modernità liquida. ISTAT: 1.7M NEET in Italia (23.1% fascia 15-29)."
  },
  {
    archetypeId: "piccolo_imprenditore_sud",
    label: "Piccolo Imprenditore Sud",
    ageMin: 35, ageMax: 60, incomeBand: "low_medium", geo: "rural", education: "secondary", householdType: "family",
    noveltySeeking: 0.25, statusOrientation: 0.45, priceSensitivity: 0.70, riskAversion: 0.65,
    emotionalSusceptibility: 0.55, identityDefensiveness: 0.75,
    conformismIndex: 0.65, authorityTrust: 0.40, delayedGratification: 0.55, culturalCapital: 0.30, locusOfControl: 0.50,
    populationShare: 0.05, marketSpendShare: 0.04,
    topicAffinities: { food: 0.9, local: 0.9, family: 0.8, automotive: 0.6, real_estate: 0.5, religion: 0.4 },
    formatAffinities: { image: 0.7, short_video: 0.6, carousel: 0.5, story: 0.4, long_article: 0.3 },
    channelUsage: { whatsapp: 0.95, facebook: 0.8, instagram: 0.5, youtube: 0.4, tiktok: 0.15, linkedin: 0.05 },
    comfortablePriceMid: 50, comfortablePriceRange: 35,
    identityProfile: { traditional: 0.8, patriotic: 0.8, local: 0.9, family_oriented: 0.8, religious: 0.5 },
    mediaDiet: { tv: 0.7, social: 0.5, radio: 0.5, newspapers: 0.3, streaming: 0.15 },
    referenceGroup: "artigiano_commerciante", rejectionGroup: "manager_corporate",
    generationalCohort: "gen_x",
    bibliographyNotes: "Polanyi: economia embedded in relazioni sociali locali. Anderson: identità regionale forte (Mezzogiorno). Hobsbawm: divario Nord-Sud come frattura storica. Piketty: disuguaglianza territoriale italiana. ISTAT: reddito medio Mezzogiorno 30% inferiore al Nord, spesa media 2.196€ vs 3.107€."
  },
];

// ─── 6 REGIMES ───────────────────────────────────────────────────────
const regimeData = [
  {
    name: "STABLE",
    label: "Stable — Baseline",
    description: "Crescita moderata, bassa inflazione, fiducia dei consumatori nella norma. Corrisponde all'Europa 1950-1973 (Judt) e alla 'società affluente' di Galbraith.",
    modPriceSensitivity: 1.0, modStatusOrientation: 1.0, modNoveltySeeking: 1.0,
    modRiskAversion: 1.0, modEmotionalSusceptibility: 1.0, modIdentityDefensiveness: 1.0,
    modConformismIndex: 1.0, modAuthorityTrust: 1.0, modDelayedGratification: 1.0,
    modCulturalCapital: 1.0, modLocusOfControl: 1.0,
    bibliographyBasis: "Judt (Postwar): Europa 1950-1973 come archetipo. Galbraith (Affluent Society): consumo come linguaggio sociale dominante. Hobsbawm (Age of Extremes): Golden Age baseline."
  },
  {
    name: "GROWTH",
    label: "Growth — Espansione",
    description: "Boom economico, ottimismo diffuso, credito facile, consumo come identità. Corrisponde al miracolo economico italiano e ai periodi di espansione post-recessione.",
    modPriceSensitivity: 0.8, modStatusOrientation: 1.3, modNoveltySeeking: 1.2,
    modRiskAversion: 0.7, modEmotionalSusceptibility: 1.0, modIdentityDefensiveness: 0.9,
    modConformismIndex: 0.9, modAuthorityTrust: 1.1, modDelayedGratification: 0.8,
    modCulturalCapital: 1.1, modLocusOfControl: 1.2,
    bibliographyBasis: "Galbraith: dependence effect massimo durante boom. Bourdieu + Veblen: conspicuous consumption aumenta. Hobsbawm: età dell'oro = innovazione come progresso. Kahneman: confidence effect riduce avversione al rischio."
  },
  {
    name: "CRISIS",
    label: "Crisis — Contrazione",
    description: "Recessione, disoccupazione in aumento, contrazione dei consumi, ansia diffusa. Corrisponde a 2008-2012 in Italia, crisi del debito sovrano.",
    modPriceSensitivity: 1.5, modStatusOrientation: 0.6, modNoveltySeeking: 0.7,
    modRiskAversion: 1.4, modEmotionalSusceptibility: 1.3, modIdentityDefensiveness: 1.2,
    modConformismIndex: 1.3, modAuthorityTrust: 0.8, modDelayedGratification: 1.2,
    modCulturalCapital: 0.9, modLocusOfControl: 0.7,
    bibliographyBasis: "McKinsey: +30-80% price sensitivity durante recessioni. Piketty: classe media compressa. Kahneman: loss aversion ×2 amplificata. Polanyi: double movement protettivo. Le Bon: contagio emotivo in crisi. Haidt: tribalismo morale si intensifica."
  },
  {
    name: "TRAUMA",
    label: "Trauma — Shock Collettivo",
    description: "Evento catastrofico (pandemia, guerra, crollo finanziario). Comportamenti estremi, panico, crollo della fiducia istituzionale. Corrisponde a COVID-19, crollo Lehman, guerre.",
    modPriceSensitivity: 1.8, modStatusOrientation: 0.3, modNoveltySeeking: 0.4,
    modRiskAversion: 1.6, modEmotionalSusceptibility: 1.5, modIdentityDefensiveness: 1.4,
    modConformismIndex: 1.5, modAuthorityTrust: 0.5, modDelayedGratification: 1.4,
    modCulturalCapital: 0.7, modLocusOfControl: 0.4,
    bibliographyBasis: "Piketty: distruzione di capitale. Arendt: atomizzazione sociale. Fromm: escape from freedom → conformismo. Kahneman: loss aversion massima sotto stress. Le Bon: masse in panico. Snyder: erosione democratica. Hoffer: true believer emerge."
  },
  {
    name: "TRANSITION",
    label: "Transition — Passaggio di Regime",
    description: "Periodo di incertezza direzionale tra due regimi. Alta varianza nelle risposte, comportamenti contraddittori. L'Italia post-2008 come caso emblematico (Judt).",
    modPriceSensitivity: 1.2, modStatusOrientation: 0.8, modNoveltySeeking: 0.8,
    modRiskAversion: 1.2, modEmotionalSusceptibility: 1.2, modIdentityDefensiveness: 1.1,
    modConformismIndex: 1.1, modAuthorityTrust: 0.7, modDelayedGratification: 1.0,
    modCulturalCapital: 0.95, modLocusOfControl: 0.8,
    bibliographyBasis: "Polanyi: double movement — oscillazione continua tra commodification e protezione. Hobsbawm: transizioni tra ere sono lunghe e irregolari. Kahneman: asimmetria — entrare in crisi è rapido, uscirne è lento (isteresi)."
  },
  {
    name: "STAGNATION",
    label: "Stagnation — Nuova Normalità",
    description: "Crescita zero prolungata, disillusione cronica, adattamento alla mediocrità. L'Italia 2012-2024: non crisi acuta, non ripresa. La 'nuova normalità' di Judt.",
    modPriceSensitivity: 1.3, modStatusOrientation: 0.7, modNoveltySeeking: 0.6,
    modRiskAversion: 1.3, modEmotionalSusceptibility: 1.1, modIdentityDefensiveness: 1.15,
    modConformismIndex: 1.2, modAuthorityTrust: 0.6, modDelayedGratification: 1.1,
    modCulturalCapital: 0.85, modLocusOfControl: 0.6,
    bibliographyBasis: "Judt: Italia post-2008 come stato che non è né crisi né stabilità. Bauman: stanchezza della modernità liquida. Galbraith: conventional wisdom si cristallizza. Hobsbawm: la Frana (1973-1991) come archetipo di stagnazione."
  },
];

async function seed() {
  console.log("Seeding 20 personas...");
  for (const p of personaData) {
    await db.insert(personas).values(p).onDuplicateKeyUpdate({
      set: { ...p, archetypeId: undefined },
    });
  }
  console.log("✓ 20 personas seeded");

  console.log("Seeding 6 regimes...");
  for (const r of regimeData) {
    await db.insert(regimes).values(r).onDuplicateKeyUpdate({
      set: { ...r, name: undefined },
    });
  }
  console.log("✓ 6 regimes seeded");

  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
