CREATE TABLE `accuracyTimeline` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brandAgentId` int NOT NULL,
	`measuredAt` timestamp NOT NULL DEFAULT (now()),
	`rollingRhoComposite` float,
	`rollingRhoResonance` float,
	`rollingRhoDepth` float,
	`rollingRhoAmplification` float,
	`totalCalibrationPosts` int,
	`postsLast30Days` int,
	`modelParamsVersion` int,
	CONSTRAINT `accuracyTimeline_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `groundTruthPosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brandAgentId` int NOT NULL,
	`platform` enum('instagram','tiktok','facebook','youtube') NOT NULL,
	`postId` varchar(200) NOT NULL,
	`postUrl` varchar(500),
	`publishedAt` timestamp NOT NULL,
	`contentType` enum('image','video','carousel','text','reel','story','short') NOT NULL DEFAULT 'image',
	`caption` text,
	`hashtags` json,
	`imageUrls` json,
	`videoUrl` varchar(500),
	`brandHandle` varchar(100),
	`brandFollowersAtTime` int,
	`metrics48h` json,
	`metrics7d` json,
	`commentAnalysis` json,
	`normResonance` float,
	`normDepth` float,
	`normAmplification` float,
	`normPolarity` float,
	`normRejection` float,
	`normComposite` float,
	`campaignDigestId` int,
	`scrapedAt` timestamp NOT NULL DEFAULT (now()),
	`normalizedAt` timestamp,
	CONSTRAINT `groundTruthPosts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `groundTruthSimulations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`groundTruthPostId` int NOT NULL,
	`brandAgentId` int NOT NULL,
	`agentPoolSize` int NOT NULL,
	`modelParams` json NOT NULL,
	`simResonance` float,
	`simDepth` float,
	`simAmplification` float,
	`simPolarity` float,
	`simRejection` float,
	`simComposite` float,
	`rawPositiveRate` float,
	`rawScrollRate` float,
	`rawShareRate` float,
	`rawRejectionRate` float,
	`rawScoreMean` float,
	`rawScoreStd` float,
	`simulatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `groundTruthSimulations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gteCalibrationRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brandAgentId` int NOT NULL,
	`totalPosts` int NOT NULL,
	`trainingPosts` int NOT NULL,
	`holdoutPosts` int NOT NULL,
	`preRhoComposite` float,
	`preRhoResonance` float,
	`preRhoDepth` float,
	`preRhoAmplification` float,
	`preRhoPolarity` float,
	`preRhoRejection` float,
	`postRhoComposite` float,
	`postRhoResonance` float,
	`postRhoDepth` float,
	`postRhoAmplification` float,
	`postRhoPolarity` float,
	`postRhoRejection` float,
	`holdoutRhoComposite` float,
	`holdoutRhoResonance` float,
	`paramsBefore` json NOT NULL,
	`paramsAfter` json NOT NULL,
	`paramDeltas` json NOT NULL,
	`contentTypeBiases` json,
	`themeWeaknesses` json,
	`outlierPosts` json,
	`maeComposite` float,
	`maeResonance` float,
	`topQuartileAccuracy` float,
	`bottomQuartileAccuracy` float,
	`calibratedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `gteCalibrationRuns_id` PRIMARY KEY(`id`)
);
