CREATE TABLE `importedCampaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brandAgentId` int,
	`sourceFormat` varchar(32) NOT NULL DEFAULT 'generic',
	`campaignName` varchar(512) NOT NULL,
	`adSetName` varchar(512),
	`adName` varchar(512),
	`platform` varchar(64) NOT NULL DEFAULT 'unknown',
	`startDate` varchar(32),
	`endDate` varchar(32),
	`impressions` int NOT NULL DEFAULT 0,
	`clicks` int NOT NULL DEFAULT 0,
	`spend` float NOT NULL DEFAULT 0,
	`currency` varchar(8) NOT NULL DEFAULT 'EUR',
	`ctr` float,
	`cpm` float,
	`cpc` float,
	`reach` int,
	`frequency` float,
	`videoViews` int,
	`conversions` int,
	`conversionRate` float,
	`roas` float,
	`objective` varchar(256),
	`status` varchar(64),
	`importedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `importedCampaigns_id` PRIMARY KEY(`id`)
);
